### ISSUE TITLE
Refactor MyApp

### ISSUE THREAD

**Issue by MayaOrnstein** [CheeseLord/smush#2]
- [x] Identify things to pull out
- [x] Actually pull them out.
- [x] Rename MyApp **Edit: or just remove it**

**Comment by CheeseLord** [comment]
We'll definitely want to separate out the physics, the graphics, and the UI (keyboard and mouse events).  There's a bunch of other logic in there, but we may need to do the refactor before we can find it.

**Comment by kronmillerg** [comment]
Subdivision of step 2:

- [x] Make app a global, make its non-init member functions into nonmember functions.
- [x] Split those functions into different modules.
- [x] See what fields can be made into globals within single modules.
- [x] Move all the init code out of main
- [x] Move MyApp to its own file? **Edit: or just remove it**

**Comment by kronmillerg** [comment]
Also we need to move MyApp to its own file at some point; it's still in main.py. **Edit: edited into previous comment.**

**Comment by kronmillerg** [comment]
MyApp is now gone, which I guess is as refactored as it can be.
